# -*- coding: utf-8 -*-
"""EnumeratingOrientedGeneOrderings

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKf46XMa1XWtpl4FfLRNcFSoS60PYQeu
"""

import itertools
n = 5
def permutation(length):
  permutations = ''
  perm_numbers = list(range(1, n+1)) + list(range(-n, 0))
  permutations = [x for x in itertools.permutations(perm_numbers, n) if len(set(map(abs, x))) == n]
  print(len(permutations))
  for i in permutations:
    print(str(i).replace('(','').replace(')','').replace(',', ''))
  return

permutation(n)